services:
  chatbot-valley-heating:
    build: .
    container_name: chatbot-valley-heating-container
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://chatbot-valley-heating-mongo-container:27017/chatbot_valley_heating
    command: npm run dev

  mongodb:
    image: mongo:8.0
    container_name: chatbot-valley-heating-mongo-container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - chatbot-valley-heating_mongo_data:/data/db
      - chatbot-valley-heating_mongo_config:/data/configdb
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh chatbot-valley-heating-mongo-container:27017/test --quiet
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s

volumes:
  chatbot-valley-heating_mongo_data:
  chatbot-valley-heating_mongo_config:
